farao-community/gridcapa-job-launcher

.github/workflows/build.yml, README.md, pom.xml, src/main/java/com/farao_community/farao/gridcapa/job_launcher/GridcapaJobLauncherApplication.java, src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobController.java, src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherConfigurationProperties.java, src/main/java/com/faraocommunity/farao/gridcapajoblauncher/GridcapaJobLauncherApplication.java, src/main/java/com/faraocommunity/farao/gridcapajoblauncher/JobController.java, src/main/java/com/faraocommunity/farao/gridcapajoblauncher/JobLauncherConfigurationProperties.java, src/main/resources/application.properties, src/main/resources/application.yml, src/test/java/com/farao_community/farao/gridcapa/job_launcher/GridcapaJobLauncherApplicationTests.java
=> Call task manager

pom.xml, src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherController.java, src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherEventsLogger.java, src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherService.java, src/main/resources/application.yml, src/main/resources/logback.xml, src/test/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherControllerTest.java, src/test/resources/application.yml
feature : convert slf4j logs to rabbitmq events with binding to calculation task
(if any of the questions/checkboxes don't apply, please delete them …
=> send custom slf4j logs as events in amqp exchange

pom.xml
=> update farao-parent and task-manager versions

pom.xml, src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherApplication.java, src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherConfigurationProperties.java, src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherController.java, src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherScheduler.java, src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherService.java, src/main/resources/application.yml, src/test/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherControllerTest.java, src/test/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherSchedulerTest.java, src/test/resources/application.yml
=> Automatic rao start

src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherScheduler.java, src/main/resources/application.yml
=> Create a separate binding for JobLauncherScheduler

pom.xml, src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherController.java, src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherService.java, src/test/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherControllerTest.java
New feature, now job-launcher changes task status to pending if the task is available in manual run and then return HTTP response.
=> Add task status change of the task in manual run

src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherAutoService.java, src/main/resources/application.yml
No
feature
launch task automatically when the status is ready
=> automatic launch

src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherAutoService.java
=> Add MDC gridcapa-task-id before sendig log to gridcapa

pom.xml, src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherController.java, src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherService.java, src/main/resources/application.yml
No
feature
Add the possibility to interrupt a running process.
=> interrupt a process

src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherService.java
No
propagate in logs MDC the task id when an order to interrupt  process is received
No
=> propagate in logs MDC the task id 

src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherService.java
Enable to launch a computation that has INTERRUPTED status
=> Be able to run interrupted computation

pom.xml
=> task-manager : 1.4.0 -> 1.13.0

src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherAutoService.java, src/test/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherAutoServiceTest.java, src/test/resources/application.yml
=> Fix consumer / subscriber in job launcher autoservice

pom.xml, src/test/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherAutoServiceTest.java
=> Update to TaskManager:1.20.0

.github/workflows/build.yml, .github/workflows/release.yml, Dockerfile, pom.xml
=> Migrate to java17

pom.xml, src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherEventsLogger.java, src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherService.java, src/test/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherSchedulerTest.java
=> Upgrade dependencies

pom.xml, src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherController.java, src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherService.java, src/test/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherAutoServiceTest.java, src/test/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherControllerTest.java, src/test/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherServiceTest.java
Depends on future release of task-manager (dependency version must be adapted in pom.xml). Doesn't compile yet.
(if any of the questions/checkboxes …
=> Configurable parameters

pom.xml, src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherConfigurationProperties.java
=> Upgrade Spring Boot 3.2 and Spring Cloud 2023

src/main/resources/application.yml, src/test/resources/application.yml
=>  set default group param correctly in spring cloud config

src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherAutoService.java, src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherCommonService.java, src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherConfigurationProperties.java, src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherScheduler.java, src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherService.java, src/main/resources/application.yml, src/test/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherAutoServiceTest.java, src/test/resources/application.yml
=> make days to add configurable

src/main/resources/application.yml, src/test/resources/application.yml
=> Harmonize application.yml

pom.xml, src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherCommonService.java, src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherConfigurationProperties.java, src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherController.java, src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherService.java, src/test/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherAutoServiceTest.java, src/test/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherCommonServiceTest.java, src/test/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherServiceTest.java, src/test/resources/application.yml
=> Add pending interrupt feature

src/main/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherCommonService.java, src/test/java/com/farao_community/farao/gridcapa/job_launcher/JobLauncherCommonServiceTest.java
=> Fix transmission of run parameters

src/main/java/com/farao_community/farao/gridcapa/job_launcher/service/JobLauncherCommonService.java, src/test/java/com/farao_community/farao/gridcapa/job_launcher/service/JobLauncherCommonServiceTest.java
=> Fix interruption by using runId and common stop exchange
